---
kind: pipeline
type: exec
name: Build all hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
  - nix --experimental-features "nix-command flakes" flake check

- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

- name: Build mobi
  commands:
  - nix build -v '.#nixosConfigurations.mobi.config.system.build.toplevel'

- name: Build rick
  commands:
  - nix build -v '.#nixosConfigurations.rick.config.system.build.toplevel'

- name: Build desktop
  commands:
  - nix build -v '.#nixosConfigurations.desktop.config.system.build.toplevel'

- name: Build flap
  commands:
  - nix build -v '.#nixosConfigurations.flap.config.system.build.toplevel'

trigger:
  branch:
  - main
  event:
  - push
  - pull_request
  - cron

---
kind: pipeline
type: exec
name: flake update

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: create result-old files
  commands:
  - nix build -v '.#nixosConfigurations.mobi.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"
  - mv result mobi-old
  - nix build -v '.#nixosConfigurations.rick.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"
  - mv result rick-old
  - nix build -v '.#nixosConfigurations.desktop.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"
  - mv result desktop-old
  - nix build -v '.#nixosConfigurations.flap.config.system.build.toplevel' --option binary-caches "https://cache.nixos.org"
  - mv result flap-old

- name: flake update
  commands:
  - nix --experimental-features "nix-command flakes" flake update --inputs-from nixpkgs
  
- name: Show git diff
  commands:
  - git diff

- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
  - nix --experimental-features "nix-command flakes" flake check

- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

- name: Build mobi
  commands:
  - nix build -v '.#nixosConfigurations.mobi.config.system.build.toplevel'
  - mv result mobi-new

- name: Build rick
  commands:
  - nix build -v '.#nixosConfigurations.rick.config.system.build.toplevel'
  - mv result rick-new

- name: Build desktop
  commands:
  - nix build -v '.#nixosConfigurations.desktop.config.system.build.toplevel'
  - mv result desktop-new

- name: Build flap
  commands:
  - nix build -v '.#nixosConfigurations.flap.config.system.build.toplevel'
  - mv result flap-new

- name: Print report
  commands:
  - echo "mobi:" && nix store diff-closures $(readlink -f mobi-old) $(readlink -f mobi-new)
  - echo "rick:" && nix store diff-closures $(readlink -f rick-old) $(readlink -f rick-new)
  - echo "desktop:" && nix store diff-closures $(readlink -f desktop-old) $(readlink -f desktop-new)
  - echo "flap:" && nix store diff-closures $(readlink -f flap-old) $(readlink -f flap-new)

trigger:
  branch:
  - main
  event:
  - push
  - pull_request

---
kind: pipeline
name: push flake update
type: docker

steps:
- name: Update flake.lock
  image: nixpkgs/nix-flakes
  commands:
  - nix flake update --inputs-from nixpkgs
  - nix flake show
  - nix flake metadata
  - nix flake check
  - nix flake check --show-trace
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Push updated flake.lock
  image: appleboy/drone-git-push
  settings:
    branch: update-flake
    remote: git@github.com:nonchris/nixos.git
    force: true
    commit: true
    force: true
    commit_message: "❄️ Update flake.lock"
    ssh_key:
      from_secret: deploy_key

trigger:
  branch:
  - main
  event:
  - push

---
kind: pipeline
name: nixfmt
type: docker

steps:
- name: nixfmt
  image: nixpkgs/nix-flakes
  commands:
  - nix-shell -p nixfmt --command "nixfmt *.nix"
  - nix-shell -p nixfmt --command "nixfmt home-manager/*.nix"
  - nix-shell -p nixfmt --command "nixfmt home-manager/*/*.nix"
  - nix-shell -p nixfmt --command "nixfmt machines/*/*.nix"
  - nix-shell -p nixfmt --command "nixfmt modules/*/*.nix"
  - nix-shell -p nixfmt --command "nixfmt users/*.nix"
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: git diff
  image: nixpkgs/nix-flakes
  commands:
  - git diff
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Push updated flake.lock
  image: appleboy/drone-git-push
  settings:
    branch: nixfmt
    remote: git@github.com:nonchris/nixos.git
    force: true
    commit: true
    force: true
    commit_message: "nixfmt */*.nix"
    ssh_key:
      from_secret: deploy_key

trigger:
  branch:
  - main
  event:
  - push
