---
kind: pipeline
type: exec
name: flake info

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata

- name: run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

---
kind: pipeline
type: exec
name: build amd64 hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build desktop
  commands:
  - nix build '.#nixosConfigurations.desktop.config.system.build.toplevel' --out-link result-desktop
  - nix path-info --closure-size -h $(readlink -f result-desktop)

- name: build flap
  commands:
  - nix build '.#nixosConfigurations.flap.config.system.build.toplevel' --out-link result-flap
  - nix path-info --closure-size -h $(readlink -f result-flap)

- name: build mobi
  commands:
  - nix build '.#nixosConfigurations.mobi.config.system.build.toplevel' --out-link result-mobi
  - nix path-info --closure-size -h $(readlink -f result-mobi)

- name: build rick
  commands:
  - nix build '.#nixosConfigurations.rick.config.system.build.toplevel' --out-link result-rick
  - nix path-info --closure-size -h $(readlink -f result-rick)

- name: upload to binary cache via s3
  commands:
  - nix run 'github:lounge-rocks/the-lounge#s3uploader'
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - cron
  - push
  - pull_request

