---
kind: pipeline
type: exec
name: flake info

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata

- name: run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

---
kind: pipeline
type: exec
name: build amd64 hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build desktop
  commands:
  - nix build '.#nixosConfigurations.desktop.config.system.build.toplevel'
- name: show closure size desktop
  commands:
  - nix path-info --closure-size -h $(readlink -f result)
  - mv result result-desktop

- name: build flap
  commands:
  - nix build '.#nixosConfigurations.flap.config.system.build.toplevel'
- name: show closure size flap
  commands:
  - nix path-info --closure-size -h $(readlink -f result)
  - mv result result-flap

- name: build mobi
  commands:
  - nix build '.#nixosConfigurations.mobi.config.system.build.toplevel'
- name: show closure size mobi
  commands:
  - nix path-info --closure-size -h $(readlink -f result)
  - mv result result-mobi

- name: build rick
  commands:
  - nix build '.#nixosConfigurations.rick.config.system.build.toplevel'
- name: show closure size rick
  commands:
  - nix path-info --closure-size -h $(readlink -f result)
  - mv result result-rick

- name: upload desktop to binary cache via s3
  commands:
  - nix copy --to 's3://nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result-desktop/) -L
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

- name: upload flap to binary cache via s3
  commands:
  - nix copy --to 's3://nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result-flap/) -L
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

- name: upload mobi to binary cache via s3
  commands:
  - nix copy --to 's3://nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result-mobi/) -L
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

- name: upload rick to binary cache via s3
  commands:
  - nix copy --to 's3://nix-cache?scheme=https&region=eu-central-1&endpoint=s3.lounge.rocks' $(nix-store -qR result-rick/) -L
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - cron
  - push
