---
kind: pipeline
type: exec
name: flake info

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

  - name: show flake show
    commands:
      - nix flake show

  - name: show flake info
    commands:
      - nix flake info

  - name: run flake checks
    commands:
      - nix flake check

---
kind: pipeline
type: exec
name: build amd64 hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build desktop
  commands:
  - nix build '.#nixosConfigurations.desktop.config.system.build.toplevel' --out-link result-desktop
  - nix path-info --closure-size -h $(readlink -f result-desktop)

- name: build flap
  commands:
  - nix build '.#nixosConfigurations.flap.config.system.build.toplevel' --out-link result-flap
  - nix path-info --closure-size -h $(readlink -f result-flap)

- name: build mobi
  commands:
  - nix build '.#nixosConfigurations.mobi.config.system.build.toplevel' --out-link result-mobi
  - nix path-info --closure-size -h $(readlink -f result-mobi)

- name: build rick
  commands:
  - nix build '.#nixosConfigurations.rick.config.system.build.toplevel' --out-link result-rick
  - nix path-info --closure-size -h $(readlink -f result-rick)

- name: upload to binary cache via s3
  commands:
  - nix run 'github:mayniklas/nixos'#s3uploader
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - cron
  - push
  - pull_request

---
kind: pipeline
type: exec
name: nix flake update - amd64

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: nix flake update
  commands:
  - nix flake update

- name: build desktop
  commands:
  - nix build '.#nixosConfigurations.desktop.config.system.build.toplevel' --out-link result-desktop
  - nix path-info --closure-size -h $(readlink -f result-desktop)

- name: build flap
  commands:
  - nix build '.#nixosConfigurations.flap.config.system.build.toplevel' --out-link result-flap
  - nix path-info --closure-size -h $(readlink -f result-flap)

- name: build mobi
  commands:
  - nix build '.#nixosConfigurations.mobi.config.system.build.toplevel' --out-link result-mobi
  - nix path-info --closure-size -h $(readlink -f result-mobi)

- name: build rick
  commands:
  - nix build '.#nixosConfigurations.rick.config.system.build.toplevel' --out-link result-rick
  - nix path-info --closure-size -h $(readlink -f result-rick)

trigger:
  branch:
  - main
  event:
  - cron
