---
kind: pipeline
type: exec
name: Build all hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: Show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata
  - nix --experimental-features "nix-command flakes" flake check

- name: Run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

- name: Build mobi
  commands:
  - nix build -v '.#nixosConfigurations.mobi.config.system.build.toplevel'

- name: Build rick
  commands:
  - nix build -v '.#nixosConfigurations.rick.config.system.build.toplevel'

- name: Build desktop
  commands:
  - nix build -v '.#nixosConfigurations.desktop.config.system.build.toplevel'

- name: Build flap
  commands:
  - nix build -v '.#nixosConfigurations.flap.config.system.build.toplevel'

trigger:
  branch:
  - main
  - update-flake
  event:
  - push
  - pull_request
  - cron