kind: pipeline
type: exec
name: Build all Hosts

platform:
  os: linux
  arch: amd64

steps:
- name: Build desktop
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
  commands:
  - nix-shell -p '(nixos{}).nixos-rebuild' --run "nixos-rebuild build -I nixos-config=./machines/desktop/configuration.nix  -v"

- name: Build flap
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
  commands:
  - nix-shell -p '(nixos{}).nixos-rebuild' --run "nixos-rebuild build -I nixos-config=./machines/flap/configuration.nix  -v"

- name: Build rick
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
  commands:
  - nix-shell -p '(nixos{}).nixos-rebuild' --run "nixos-rebuild build -I nixos-config=./machines/rick/configuration.nix  -v"

- name: Build mobi
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable
  commands:
  - nix-shell -p '(nixos{}).nixos-rebuild' --run "nixos-rebuild build -I nixos-config=./machines/mobi/configuration.nix  -v"

trigger:
  branch:
  - main
  event:
  - push
  - cron
